### ISSUE TITLE
MOT17 data format

### ISSUE THREAD

**Issue by ghost** [yinizhizhu/GNMOT#1]
Hi, 
I want to reproduce the results of your great work.
But I met some difficulties preparing the data for testing.
I have trained App and Motion GN with only MOT16 but no MOT17 (I am not sure whether you use data from MOT17 during training.)
But I noticed that the test needs MOT17 data.
But the data format you have explained in your README is not the same as that in your code.
I think you missed some explanation about how to run `copyfile.py` in `GN`, `App2 `, `Motion1`. 
Looking forward to your reply.

**Comment by yinizhizhu** [comment]
Q1. I am not sure whether you use data from MOT17 during training.
A1. We train and test our graph networks with MOT16 and MOT17 separately. For instance, on MOT16, we ONLY use the data from MOT16 to train our graph networks.

Q2. The data format you have explained in your README is not the same as that in your code.
A2. This may be caused in my cleaning code process. We would appreciate it very much if you tell us what the difference is, and we will fix it.

Q3. How to run copyfile.py in GN, App2 , Motion1.
A3. After finishing the tracking process, you can run `copyfile.py` to collect all the tracking results into the same directory.
