### ISSUE TITLE
Some questions about your code and model performance

### ISSUE THREAD

**Issue by ghost** [yinizhizhu/GNMOT#3]
Hi, 

Thanks for your reply for my other two issues.
I met some problems.
Q1: What is type `POI`?
Q2: I replace `POI` with the public detections from MOT17, and run evaluation code (motmetrics) on **trian set**. But got very low MOTA (21.9%). What's wrong with that?
Q3: The BaiduPan link in the README is invalid. Could you please fix it up?

Thanks again.

**Comment by yinizhizhu** [comment]
Hi,

Q1: What is type POI?
A1. POI is the work [46] cited in our paper.

[46] F. Yu, W. Li, Q. Li, Y. Liu, X. Shi, and J. Yan. POI: Multiple object tracking with high performance detection and appearance feature. In G. Hua and H. J´egou, editors, Computer Vision – ECCV 2016 Workshops, pages 36–42, Cham, 2016. Springer International Publishing.

Q2: I replace POI with the public detections from MOT17, and run evaluation code (motmetrics) on trian set. But got very low MOTA (21.9%). What's wrong with that?
A2. Something wrong happended, but I have no idea about that. You can find more details about our method in our 
[paper](http://www.vie.group/media/pdf/0028_Wsjq0ED.pdf).

Q3: The BaiduPan link in the README is invalid. Could you please fix it up?
A3. Thanks for your correction. Now, it has been fixed. Actually, the first link is valid all the time.
